Ruby/rails_box/dojodashboard/config/routes.rb
Rails.application.routes.draw do
  resources :dojos

end

Ruby/rails_box/dojodashboard/app/models/dojo.rb
class Dojo < ActiveRecord::Base
end

Ruby/rails_box/dojodashboard/app/controllers/dojos_controller.rb
class DojosController < ApplicationController
  def index
    @dojos = Dojo.all
  end
end

Ruby/rails_box/dojodashboard/app/helpers/dojos_helper.rb
module DojosHelper
end

Ruby/rails_box/dojodashboard/app/views/dojos/_form.html.erb
<%= form_for(@dojo) do |f| %>
  <% if @dojo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dojo.errors.count, "error") %> prohibited this dojo from being saved:</h2>

      <ul>
      <% @dojo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :branch %><br>
    <%= f.text_field :branch %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby/rails_box/dojodashboard/app/views/dojos/edit.html.erb
<h1>Editing Dojo</h1>

<%= render 'form' %>

<%= link_to 'Show', @dojo %> |
<%= link_to 'Back', dojos_path %>

Ruby/rails_box/dojodashboard/app/views/dojos/index.html.erb
<h1>Listing <%= pluralize(@dojos.count, "Dojo") %></h1>

<table>
	<thead>
		<th>Coding Dojo Branch</th>
		<th>Street</th>
		<th>City</th>
		<th>State</th>
	</thead>
	<tbody>
		<% @dojos.each do |dojo| %>
		<tr>
			<td><%= dojo.branch %></td>
			<td><%= dojo.street %></td>
			<td><%= dojo.city %></td>
			<td><%= dojo.state %></td>
		</tr>
		<% end %>
	</tbody>
</table>

Ruby/rails_box/dojodashboard/app/views/dojos/new.html.erb
<h1>New Dojo</h1>

<%= render 'form' %>

<%= link_to 'Back', dojos_path %>

Ruby/rails_box/dojodashboard/app/views/dojos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Branch:</strong>
  <%= @dojo.branch %>
</p>

<p>
  <strong>Street:</strong>
  <%= @dojo.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @dojo.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @dojo.state %>
</p>

<%= link_to 'Edit', edit_dojo_path(@dojo) %> |
<%= link_to 'Back', dojos_path %>

Ruby/rails_box/dojodashboard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DojoDashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>